@startuml

package Entities {
    class Employee {
        - Long id
        - String name
        - String role
        + Long getId()
        + void setId(Long id)
        + String getName()
        + void setName(String name)
        + String getRole()
        + void setRole(String role)
        + boolean equals(Object o)
        + int hashCode()
        + String toString()
    }
}

package Controllers {
    class EmployeeController {
        - EmployeeRepository repository
        + List<Employee> all()
        + Employee newEmployee(Employee newEmployee)
        + Employee one(Long id)
        + Employee replaceEmployee(Employee newEmployee, Long id)
        + void deleteEmployee(Long id)
    }
}


EmployeeController --> EmployeeRepository
EmployeeController --> Employee
@enduml
